### ISSUE TITLE
Which parameter corresponds to tau?

### ISSUE THREAD

**Issue by QuillDurand** [LIJUNYI95/SuperAdam#1]
More generally, how do the parameters in the code correspond to the parameters in the paper.
the code has lr, beta, eps, c, m, gamma, global_size, coordinate_global_size, use_adam
the paper has (or at least lists in the experiments section) k, m, c, gamma, and tau.

So, c, m, and gamma are pretty clear, but k and tau are unaccounted for, and beta and the boolean variables are unclear. (for that matter, I don't actually see the lr used for superAdam mentioned in the experiments as something separate from gamma, unless it's under another name)

**Comment by LIJUNYI95** [comment]
1. 'tau' corresponds to 'use-adam' flag in the code;
2. we provide multiple choices of H matrice in the paper, and they are represented by the boolean variables: global_size, coordinate_global_size;
3. 'lr' corresponds to 'k' in the paper;
More details and some instructions are expected soon.

**Comment by QuillDurand** [comment]
So, if I'm understanding correctly, SuperAdam(model.parameters(), lr=1, m=100, c=40, gamma=0.01, use_adam=True, global_size=True), corresponds to the tau-1 configuration used for Resnet-34 on imagenet in the experiments?

**Comment by LIJUNYI95** [comment]
No, tau=1 is the variance reduction case, you should set 'use_adam' be false

**Comment by QuillDurand** [comment]
SuperAdam(model.parameters(), lr=1, m=100, c=40, gamma=0.01, use_adam=False, global_size=True), then? Is global_size the parameter for the case 1 H matrix?

**Comment by LIJUNYI95** [comment]
code is updated.
